vich_uploader:
    db_driver: orm

    mappings:
        student_images:
            uri_prefix: '%app.path.student_images%'
            upload_destination: '%kernel.project_dir%/public/images/Student_profile'
