#index:
#    path: /
#    controller: App\Controller\DefaultController::index
student_registration:
    path: /registration
    controller: App\Controller\UserController::studentRigAction

#view_data:
#    path: /student-login
#    controller: App\Controller\UserController::viewUserDataAction
login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST
student_home:
    path: /home
    controller: App\Controller\UserController::homeAction
    methods: GET|POST

dashboard:
    path: /student-login/dashboard
    controller:  App\Controller\UserController::viewUserDataAction
#    methods: GET|POST

user_dashboard:
    path: /userdashboard
    controller: App\Controller\UserController::UserdashboardAction
login_student:
    path: /student
    controller: App\Controller\UserController::viewUserDataAction
    methods: GET|POST

update_student:
    path: /update/stduent/{id}
    controller:  App\Controller\UserController::updateStudent
    methods: GET|POST
